@startuml inline_umlgraph_1.svg
class BatchCollect {
  + call()
}

BatchCollect --> SortByClause : sort order
BatchCollect --> UusiObjekti : magiaa

note right of  BatchCollect
Responsibilities:
- Collects Rows

Collaborators:
- SortByClause
end note
@enduml
@startuml inline_umlgraph_2.svg
!include src/main/java/com/teragrep/functions/dpf_02/BatchCollect.java!0
!include src/main/java/com/teragrep/functions/dpf_02/SortByClause.java!0
!include src/main/java/com/teragrep/functions/dpf_02/UusiObjekti.java!0
@enduml
@startuml inline_umlgraph_3.svg
class SortByClause {
  - getLimit()
}

note right of  SortByClause
Responsibilities:
- Sorts Rows

Collaborators:
- ConvertIPStringToInt
end note
@enduml
@startuml inline_umlgraph_4.svg
class UusiObjekti {
  + jotain()
}

note right of UusiObjekti
Responsibilities:
 - irresponsible
end note
@enduml
