on:
  push:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      # Create javadoc content
      - name: Publish JavaDoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v3.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 11
          target-folder: "javadoc/${{ steps.extract_branch.outputs.branch }}"
          project: maven
          without-deploy: true
        env:
          MAVEN_OPTS: "-Dmaven.javadoc.failOnError=false"
      # Install doxygen
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install doxygen
      # Generate doxygen docs
      - name: Generate Doxygen docs
        run: doxygen Doxyfile
        env:
          OUTPUT_DIRECTORY: "doxygen/${{ steps.extract_branch.outputs.branch }}"
      # Debug
      - name: Debug
        run: ls -laF && git status
